version: "3.8"
services:
  service:
    image: jockeftw/ninjakatt
    restart: always
    environment:
      - PLUGINDIR=/plugins
      - APPDATA=/config
      - PLUGINS=["files", "logger", "qbittorrent", "movies", "webserver", "torrentrss", "telegram"]
    ports:
      - "8080:8585"
    volumes:
      - "C:\\Users\\linds\\AppData\\Roaming\\ninjakatt:/config"
      - "d:\\torrents:/downloads"
